### ISSUE TITLE
Are we supposed to use 0.9.7?

### ISSUE THREAD

**Issue by ndevenish** [yayahjb/cbflib#60]
I'm left unsure if 0.9.7 is supposed to be used externally, or if it's just an internal/alpha partial release before something considered ready for production:
- pycbf apparently un-regenerated (https://github.com/yayahjb/cbflib/issues/59)
- https://github.com/cbflib/cbflib is not updated (which my understanding was to be the new home)
- The README still says 0.9.6: https://github.com/yayahjb/cbflib/blob/5232590ec6cc05bb2705acc3413ea598263854da/README#L14-L18
- `CBFlib.html` still says 0.9.**5**: https://github.com/yayahjb/cbflib/blob/5232590ec6cc05bb2705acc3413ea598263854da/doc/CBFlib.html#L111-L115
- The official(?) web site http://www.bernstein-plus-sons.com/software/CBF/ still says 0.9.6
- The `CMakeLists.txt` still says 0.9.6 (and tries to download the 0.9.6 test data): https://github.com/yayahjb/cbflib/blob/5232590ec6cc05bb2705acc3413ea598263854da/CMakeLists.txt#L5
- **The CBFlib internal version still says that it is 0.9.6** (Since this is the most important actual baked-in version number, this is possibly the biggest signal that I shouldn't be using 0.9.7): https://github.com/yayahjb/cbflib/blob/5232590ec6cc05bb2705acc3413ea598263854da/include/cbf.h#L262-L264
- The github [release page](https://github.com/yayahjb/cbflib/releases/tag/CBFlib-0.9.7) says "Initial CBFlib-0.9.7" whereas the previous release says "CBFlib-0.9.6 Production Release"
- The branch https://github.com/yayahjb/cbflib/tree/CBFlib-0.9.7-devel on this repository is still actively under development
- The github PR https://github.com/cbflib/cbflib/pull/1 for development is unmerged _but up-to-date with the CBFlib-devel branch, indicating that it is actively maintained_

It is fine if this is the case - I am just unsure if I should put time into diagnosing the issues I'm having or whether I should just wait for a complete release!

**Comment by yayahjb** [comment]
Dear Nick,
  Since the upgrade of CBFlib main to 0.9.7, I have tried to keep main and
the 0.9.7 branch in sync except for iffy
fixes, but you seem to have found something that drifted unintentionally.
I leave it to you, Aaron and Billy to decide
what part of what is there now is essential to you now and I will rejoin
the effort in late September.
 I really am out of bandwidth right now.
  Regards,
    Herbert

**Comment by ndevenish** [comment]
Okay, so we have to deal with things as they are for now. Thanks for clarifying.
